In [2]:
a = (1,2,3,4)
b = ["a", "b", "c", "d", "e"]
c = [True, False, True, False]

for x, y, z in zip(a,b,c):
    print(x, y, z)

1 a True
2 b False
3 c True
4 d False


In [4]:
a = [0]

if a[0]:
    

int

In [12]:
#Comprehension lists

lst = list(range(10000))
i =[i for i in lst if i %2 == 0]

In [ ]:
a = np.random.random((5,2,3))

In [58]:
import numpy as np

print(a)
print("----------------")
b = np.mean(a, axis=2)
c = a[4:5,1:2,0:1]
print(c)

[[[0.06228292 0.56108428 0.05915523]
  [0.83626047 0.64766806 0.50279616]]

 [[0.38891467 0.8639832  0.11908124]
  [0.00431914 0.17716779 0.88819138]]

 [[0.1009202  0.79729151 0.09183432]
  [0.6388499  0.64295348 0.92233578]]

 [[0.75177468 0.43934877 0.98703869]
  [0.01470279 0.52278271 0.78310385]]

 [[0.91137718 0.73498583 0.17939329]
  [0.04793165 0.14739115 0.98208601]]]
----------------
[[[0.04793165]]]
